// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9NifHuk1vpeT-VelPljv659YMhkZf1N0',
    appId: '1:932579730197:web:0c051c92afaca234137f1c',
    messagingSenderId: '932579730197',
    projectId: 'leprekonapp',
    authDomain: 'leprekonapp.firebaseapp.com',
    storageBucket: 'leprekonapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf5k0kTR0a6llA7Dwha8ZL63yBP_qMErc',
    appId: '1:932579730197:android:257dc9554ee489e3137f1c',
    messagingSenderId: '932579730197',
    projectId: 'leprekonapp',
    storageBucket: 'leprekonapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdHmJ470dIiVB1WCs8WXxXMphe1PbK1A',
    appId: '1:932579730197:ios:719c935291ad98c3137f1c',
    messagingSenderId: '932579730197',
    projectId: 'leprekonapp',
    storageBucket: 'leprekonapp.appspot.com',
    iosBundleId: 'com.example.leprekonProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdHmJ470dIiVB1WCs8WXxXMphe1PbK1A',
    appId: '1:932579730197:ios:719c935291ad98c3137f1c',
    messagingSenderId: '932579730197',
    projectId: 'leprekonapp',
    storageBucket: 'leprekonapp.appspot.com',
    iosBundleId: 'com.example.leprekonProgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9NifHuk1vpeT-VelPljv659YMhkZf1N0',
    appId: '1:932579730197:web:624f3d1ef3dcc40b137f1c',
    messagingSenderId: '932579730197',
    projectId: 'leprekonapp',
    authDomain: 'leprekonapp.firebaseapp.com',
    storageBucket: 'leprekonapp.appspot.com',
  );
}
